name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libsqlite3-dev ffmpeg libsdl2-dev libsdl2-image-dev \
            libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev \
            libavcodec-dev zlib1g-dev ccache git libffi-dev libssl-dev libltdl-dev libgmp-dev zip unzip

      - name: Install Buildozer & Cython
        run: |
          pip install --upgrade pip setuptools
          pip install buildozer cython==0.29.33

      - name: Build APK with Buildozer
        run: |
          yes | buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: bin/*.apk
